### ISSUE TITLE
or_glm for glm(family=poisson) model?

### ISSUE THREAD

**Issue by landge** [pat-s/oddsratio#36]
Hi,
thank you for this great package!

I was wondering if it is ok to use the or_glm function on a glm model of the
poisson family?
I've tried it and the results look ok, but I don't know if the package was desgined to accept glm(poisson) models. 

Thanks for your help!

**Comment by pat-s** [comment]
As long as you estimate probabilities/odds, you should be fine. Haven't used poisson models myself in practice yet though.
